import { IWorkflowConfigurationSection } from '../config-section.model';

export const ddexSections: IWorkflowConfigurationSection[] = [
  {
    title: 'Properties',
    fields: [
      {
        key: 'INCLUDE_KOSOVO',
        label: 'Include Kosovo in Definition of World',
        type: 'checkbox',
        placeholder: '',
        values: [],
        description: 'Include Kosovo in Territories',
        defaultValue: 'false',
        required: false,
      },
      {
        key: 'SPOTIFY_RELEASE_TYPE',
        label: 'Spotify Release Type',
        type: 'checkbox',
        placeholder: '',
        values: [],
        description: 'Include Spotify Release Type in XML',
        defaultValue: 'false',
        required: false,
      },
      {
        key: 'USE_DATE_TIME',
        label: 'Use Date Time',
        type: 'checkbox',
        placeholder: '',
        values: [],
        description: 'Use Date Time',
        section: 'properties',
        defaultValue: 'false',
        required: false,
      },
      {
        key: 'INCLUDE_ATMOS',
        label: 'Include Atmos Assets',
        type: 'checkbox',
        placeholder: '',
        values: [],
        description: 'Include Kosovo in Territories',
        defaultValue: 'false',
        required: false,
      },
    ],
  },
  {
    title: 'Transcodes & Download Links',
    fields: [
      {
        key: 'PRODUCT_TRANSCODE',
        label: 'Product Asset Transcode Type',
        type: 'select',
        placeholder: 'Transcode Type to be used for Product Assets',
        values: ['NONE', 'JPG'],
        defaultValue: 'NONE',
        description: 'Transcode Type to be used for Product Assets',
        section: 'Transcodes',
        required: false,
      },
      {
        key: 'AUDIO_TRANSCODE',
        label: 'Audio Transcode Type',
        type: 'select',
        placeholder: 'Transcode Type to be used for Audio',
        values: ['NONE', 'MP3', 'FLAC', 'STANDARD_DEFINITION'],
        defaultValue: 'NONE',
        description: 'Transcode Type to be used for Audio',
        section: 'Transcodes',
        required: false,
      },
      {
        key: 'DOWNLOAD_LINK',
        label: 'Assets to Replace with Download Links',
        type: 'select',
        placeholder: 'Assets to Replace with Download Links',
        values: [
          'NONE',
          'TRACK_ASSETS',
          'VIDEO_ASSETS',
          'AUDIO_ASSETS',
          'ALL_ASSETS',
          'PRODUCT_ASSETS',
        ],
        defaultValue: 'NONE',
        description:
          'The Selected Type of Assets Will Be Replaced with Download Links, If Not Present The Download Links Are Generated',
        section: 'Download Links',
        required: false,
      },
    ],
  },
  {
    title: 'Asset Naming & Folder Structure',
    fields: [
      {
        key: 'SIMPLE_ASSET_NAMING',
        label: 'Simple Asset Naming',
        type: 'checkbox',
        placeholder: '',
        values: [],
        description: 'Simple Asset Naming',
        defaultValue: 'false',
        required: false,
      },
      {
        key: 'RELEASE_TYPE',
        label: 'Release Type',
        type: 'select',
        placeholder: 'Folder structure will be created based on Release Type',
        values: ['STANDARD', 'BATCHED', 'RELEASE_BY_RELEASE'],
        defaultValue: 'STANDARD',
        description: 'Folder structure will be created based on Release Type',
        required: false,
      },
    ],
  },
];
